export class images {
 myimage:string="assets/images/leo-fan-made-poster.png"
  myimage2:string="assets/images/wallpaperflare.com_wallpaper.jpg"
  myimage3:string="assets/images/13453.jpg"
  myimage4:string="assets/images/wp2131761.jpg"
  logo:string="assets/logo edit.png"
  dia:string="assets/images/dia.jpg"
  diaposter:string="assets/images/Dia-movie-is-now-streaming-on-Amazon-Prime-Video.jpg"
  maaveran:string="assets/images/maaveran.jpg"
  maaveranposter:string="assets/images/maaveran poster.jpg"
  hridhayam:string="assets/images/Hridayam-2.jpg"
  hridhayamposter:string="assets/images/hridhayam poster.jpg"
  jailer:string="assets/images/jailer.jpg"
  jailerposter:string="assets/images/jailer poster.jpg"
  leoposter:string="assets/images/vijay-leo-movie-stills-hd-wallpapers-1200px-4288182.jpg"
  interposter:string="assets/images/8e0dab8699be85720ce55845065bf6dc.jpg"
  avengerposter:string="assets/images/wallpapersden.com_avengers-endgame-international-poster_3378x5000.jpg"
  gameofthrones:string="assets/images/154641913.jpg"
}